### ISSUE TITLE
Deleting a file prior to running prevent-forbidden-code results in error

### ISSUE THREAD

**Issue by KeithPepin** [KeithPepin/prevent-forbidden-code#4]
Deleted a file from a project and upon running the prevent-forbidden-code check, received the following error:

```
[ >>> BEGIN PRE-COMMIT FORBIDDEN CODE CHECK ]
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'config/protractor.conf.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/keithpepin/gyda/git-repo/gaf-protractor-config/node_modules/prevent-forbidden-code/index.js:62:31
    at Array.forEach (native)
    at /Users/keithpepin/gyda/git-repo/gaf-protractor-config/node_modules/prevent-forbidden-code/index.js:61:11
    at Git.<anonymous> (/Users/keithpepin/gyda/git-repo/gaf-protractor-config/node_modules/prevent-forbidden-code/node_modules/simple-git/src/git.js:929:18)
    at Git.<anonymous> (/Users/keithpepin/gyda/git-repo/gaf-protractor-config/node_modules/prevent-forbidden-code/node_modules/simple-git/src/git.js:1199:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)

```

**Comment by KeithPepin** [comment]
Fixed by [d8ad4ac8bf3bf603238a4e13e2aab283474c76bd](https://github.com/KeithPepin/prevent-forbidden-code/commit/d8ad4ac8bf3bf603238a4e13e2aab283474c76bd)
